### ISSUE TITLE
BeaconDetected not firing?

### ISSUE THREAD

**Issue by colinwurtz** [huysentruitw/win-beacon#11]
I'm to run the sample project and detect an iBeacon I have sitting on my desk. I changed the PID and VID to correspond with my [USB dongle](http://www.amazon.com/Inateck-Bluetooth-Wireless-Compatible-Playback/dp/B00N2E3ZHG). Used Zadig to load the WinUSB Driver onto the device.

Running this code, it just seems to run without detecting anything. Am I missing anything or is there anything else I can try? I know the beacon is advertising because I have the same dongle in a Raspberry Pi nearby and it is picking up the beacon. Running Windows 7.

    static void Main(string[] args)
        {
            Console.WriteLine("starting up...");            
            
            using (var hub = new BeaconHub(0x0A5C, 0x21EC))
            {
                hub.BeaconDetected += (sender, e) => Console.WriteLine(e.Beacon.ToString());

                Console.ReadKey();
            }
        }

**Comment by huysentruitw** [comment]
Can you test if you can let it advertise as a Beacon? As of now, I could only test with one chip-type, so it is possible that this minimalistic stack is not generic enough to run on a broader range of BT4.0 dongles.

What stack are you running on the Raspberry PI?

**Comment by colinwurtz** [comment]
Thanks for the reply... Yes I was able to get it to advertise as a beacon. Seems like it might be a similar situation to #4.

I'm using node.js with this library to scan and detect beacons.
https://github.com/sandeepmistry/node-bleacon

I'm not doing anything else on the Pi besides scanning and logging out info when a beacon is detected. The prerequisites for that library were to install these on the Pi.
`sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev`

**Comment by huysentruitw** [comment]
Probably some HCI init commands are missing. I will look into this ASAP.

**Comment by huysentruitw** [comment]
I've added two commands for setting the host and le event masks which will probably solve your problem. It's a wild guess, because the dongles I have seem to work out of the box without setting the masks. Anyway, other libraries are configuring them so it surely won't do any harm :)

I have build a new NuGet package v1.1.0.63, can you please retest with this version and give some feedback?

**Comment by colinwurtz** [comment]
Left the beacons at work... will test Monday morning and let you know.
Thanks.

**Comment by huysentruitw** [comment]
Hardly can't wait :)

**Comment by colinwurtz** [comment]
I tried the version `Install-Package WinBeacon -Version 1.1.0.63` and also the newer one (1.1.0.67) and neither of them worked. Didn't change the code at all and it's still not picking up any nearby iBeacons. 

Advertising as an Beacon still works though. Is there any more debugging or things I can try and my end?

**Comment by huysentruitw** [comment]
I don't know your expert-level, but can you check out the code from master and apply this 
[patch.diff.txt](https://github.com/huysentruitw/win-beacon/files/61792/patch.diff.txt)

Just update VID & PID in the sample and run it. While running, incoming and outgoing data will be logged into the Visual Studio Output window. If you could send me that data while there is one (i)Beacon in range, that would be very helpful.

Thanks

**Comment by colinwurtz** [comment]
First first time applying a patch, but I think I did it right. These are the steps I took...

1. Cloned master branch: `git clone https://github.com/huysentruitw/win-beacon.git`
2. Downloaded patch file and placed it in git folder
3. ran `git apply patch.diff.txt`
4. Changed code in sample project to this:

```c#
 using (var hub = new BeaconHub(0x0A5C, 0x21EC))
            {
                hub.BeaconDetected += (sender, e) => Console.WriteLine(e.Beacon.ToString());
                
                //hub.EnableAdvertising(new Beacon("B9407F30-F5F8-466E-AFF9-25556B57FE6D", 1000, 2000, -52));
                
                Console.ReadKey();
            }
```
5. Attached is the output from View - Output(Debug) in Visual Studio.


[debug_output.txt](https://github.com/huysentruitw/win-beacon/files/61871/debug_output.txt)

**Comment by huysentruitw** [comment]
Can you apply this patch [patch2.diff.txt](https://github.com/huysentruitw/win-beacon/files/62440/patch2.diff.txt) and test again with the sample?

**Comment by colinwurtz** [comment]
I think it may have worked? Here's the output from the console and the debug output.
[debug output -2.txt](https://github.com/huysentruitw/win-beacon/files/62727/debug.output.-2.txt)

![winbeacon-console](https://cloud.githubusercontent.com/assets/3066044/11815419/418910f2-a311-11e5-8edb-db0173bb9e5c.png)

**Comment by huysentruitw** [comment]
That looks good, but I wonder why you only have one line. Normally a beacon resends its advertising data on a fixed interval. Do you see resends or only one occurrence?

**Comment by huysentruitw** [comment]
Ok, my mistake, my previous patch also turned on filter duplicates which causes this behavior. So seems like we have a fix for your situation. Updated NuGet package is coming!

**Comment by huysentruitw** [comment]
Can you please test NuGet package 1.1.0.71? Thanks for your support!

**Comment by colinwurtz** [comment]
Tested with new package and it works now. Thanks for the support!
