### ISSUE TITLE
Can't seem to connect to USB device

### ISSUE THREAD

**Issue by randomxxxx** [huysentruitw/win-beacon#12]
I have a compatible Pluggable device and this line fails: using (var hub = new BeaconHub(pid, vid)) with USB device not found.  I have tried 0x0A5C as the PID and 0x21E8 as the VID (also tried converting these into Ints but that didn't work either).  The device shows up in the Device Manager and seems to work fine.  Any ideas?  Thanks!

**Comment by colinwurtz** [comment]
@randomxxxx  I was able to find my VID and PID using [Zadig](http://zadig.akeo.ie/). I configmed BCM20702A0 was my dongle by adding it and removing it and seeing what popped up under devices in Zadig. 

![image](https://cloud.githubusercontent.com/assets/3066044/11635140/7af36622-9cda-11e5-9543-71fbaafb2b8a.png)

    using (var hub = new BeaconHub(0x0A5C, 0x21EC))

**Comment by randomxxxx** [comment]
Thank you very much for the reply and link - works great!  It had looked like the standard driver needed to be replaced but I wasn't sure or knew how to do so.
