### ISSUE TITLE
BeaconHub VID PID ?

### ISSUE THREAD

**Issue by Porsborgvej** [huysentruitw/win-beacon#13]
Hi

First off thanks for this project, hope I can get it to work on my little project.

Question : I checked my bluetooth usb settings and can see that is runs on the default (0x0A5C, 0x21E8), but when I run it I just get "throw new WinBeaconException("USB device not found, check VID & PID");" ??

I have a LM506 USB dongle from lm-technologies "Chipset : BCM20702".

**Comment by colinwurtz** [comment]
Check out my instructions about loading the generic driver on #12.

**Comment by Porsborgvej** [comment]
Ahh thanks, I tryed the Zadig but it failed to install the winusb.

**Comment by huysentruitw** [comment]
I too think that the WinUSB driver is the only thing missing. Where is it failing? Can you add a screenshot of the failure or Zadig tool setup?

**Comment by huysentruitw** [comment]
Any news on this @Porsborgvej  ?

**Comment by Porsborgvej** [comment]
Hi, yeah after it falied I did a reboot of the pc, and it worked. it was on a windows 7 pc.
I also tryed it on a windows 8/10 worked like a charm. :+1:
