### ISSUE TITLE
Unable to install on an Universal App

### ISSUE THREAD

**Issue by MiguelRipoll23** [huysentruitw/win-beacon#15]
Is there anything I can do? Thanks.

> Install-Package : WinBeacon 1.1.0.75 is not compatible with UAP,Version=v10.0.
> At line:1 char:1
> + Install-Package
> + ~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : LibUsbDotNet 2.2.8 is not compatible with UAP,Version=v10.0.
> At line:1 char:1
> + Install-Package
> + ~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : Some packages are not compatible with UAP,Version=v10.0.
> At line:1 char:1
> + Install-Package
> + ~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : WinBeacon 1.1.0.75 is not compatible with UAP,Version=v10.0 (win10-arm).
> At line:1 char:1
> + Install-Package
> + ~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by huysentruitw** [comment]
I'm afraid Univarsal Apps are beyond the scope of this project. If your target is Windows 10, then you don't need this library and should be able to use the native API's.

**Comment by MiguelRipoll23** [comment]
Thanks for the response, you are correct.
