### ISSUE TITLE
C++ compatibility

### ISSUE THREAD

**Issue by Grauerf** [huysentruitw/win-beacon#16]
Hey,
at first thank your for winbeacon! It already helped me a lot.
I am working on a project written in C++ and I try to add the Bluetooth Low Energy stack there. 
Do you have any idea about how to make it work?
I started writing a COM Wrapper around your project but it seems to be quite complicated...

Thanks!

**Comment by huysentruitw** [comment]
Sorry for my late answer, but for C++ I suggest you look into https://github.com/sandeepmistry/node-bluetooth-hci-socket#windows and https://github.com/sandeepmistry/noble by @sandeepmistry
