### ISSUE TITLE
Cannot receive data from etimote beacons

### ISSUE THREAD

**Issue by amigobv** [huysentruitw/win-beacon#2]
I am using an Lenovo Ultrabook yoga with Windows 8.1 OS and Bluetooth 4.0 BLE.

I installed WinBeacon on my notebook by using NuGet Console. I replaced the Bluetooth driver with the WinUSB driver by using the Zadig tool. Then I downloaded the WinBeacon sample project and I started the program. Using this program I was able to send beacon messages but I couldn't receive any message from other beacon devices.

Changing the scanning interval of the LeController didn't helped at all.

**Comment by huysentruitw** [comment]
What are you using as beacon? Can you successfully detect the beacon with an other device?

**Comment by amigobv** [comment]
I'm using Estimote Beacons and yes, I have no problem detecting those Beacons with my Android Smartphone. 

http://estimote.com/

**Comment by huysentruitw** [comment]
Wasn't able to test with real Estimote beacons, but did test with Estimote app on the iPad (Virtual Beacon) and it works. So I suspect your Bluetooth chip is not fully compatible.

Can you figure out more details about the BT chip used in your Lenovo Ultrabook from the device manager?

**Comment by huysentruitw** [comment]
Please re-open if you have more info

**Comment by alfanpresekal** [comment]
I have same problem with amigobv , I am using BLE dongle , VendorID = 0x0A5C, ProductID = 0x21E8;  Do you have any sugestion?

**Comment by alfanpresekal** [comment]
Anyway, last time my error was because I juts implement you code directly huysentruitw , but now it work by change the value of VendorID and ProductID. It can broadcast (advertise) data, I can read the data using android. 

But for beacon detection, it still did not work. Do you have any idea why?

Many thanks
