### ISSUE TITLE
Can this library be modified to support the google Eddystone protocol?

### ISSUE THREAD

**Issue by sbarne3** [huysentruitw/win-beacon#20]
https://github.com/google/eddystone

**Comment by huysentruitw** [comment]
It looks like it should work. They're using a compatible format, the beacon CompanyId should contain the Eddystone identifier (0xAAFE) and Uuid should contain the beacon UUID just like other beacons.

**Comment by huysentruitw** [comment]
Little bit too fast, looks like only the Eddystone-UID frame will be supported and not the other frame types. But I'm certainly interested to support these. Any good recommendations for a Eddystone beacon I should order?

**Comment by huysentruitw** [comment]
Will close for now, feel free to re-open this issue.
