### ISSUE TITLE
Advertising not working?

### ISSUE THREAD

**Issue by TheScribbler** [huysentruitw/win-beacon#22]
Thank you very much for this great Project!

I've successfully compiled the Project on NET 3.5 Client Profile Settings and the Receiver works great. I can detect any beacons near my Bluetooth dongle. I've started the Advertising as a beacon as well (just like your sample code), but I can't receive anything on my other devices (like an android phone). The same dongle worked fine under Linux, I was able to use it as a Beacon together with my android phone successfully.

Do you have any hints that you can give me, why the transmit doesn't work?
```C#
using (var hub = new BeaconHub(0x0A12, 0x0001))
{
    hub.BeaconDetected += (sender, e) => Console.WriteLine(e.Beacon.ToString());
    hub.EnableAdvertising(new Beacon("B9407F30-F5F8-466E-AFF9-25556B57FE6D", 1000, 2000, -52));
    Console.ReadKey();
}
```

With further testing, I've hard-encoded the hcitool-command that I was using under Linux in the program:
```C#
public void EnableAdvertising(byte[] advertisementData)
        {
            byte[] DEBUGadvertisementData = { 02, 01, 26, 26, 255, 76, 00, 02, 21, 226, 10, 57, 244, 115, 245, 75, 196, 161, 47, 23, 209, 173, 07, 169, 97, 00, 00, 00, 00, 200, 00};
            SendCommand(new LeSetAdvertisingDataCommand(DEBUGadvertisementData));
            SendCommand(new LeSetAdvertisingEnableCommand(true));
        }
```

With this code, the advertisment WORKS. Up to "02, 01, 26, 26, 255, 76, 00, 02, 21," everything is identical. As I don't really know what I've changed by this (the hcitool-code comes from http://www.orangenarwhals.com/2014/06/bluetooth-low-energy-4-0-on-ubuntu-13-10-advertisements-sending-and-receiving/), can this Information maybe lead you to why the sample code does not work?

**Comment by huysentruitw** [comment]
Is #23 a fix for this?

**Comment by TheScribbler** [comment]
No, it's not a fix, sorry. I can only advertise, when I hard-code the advertismentData as shown above.

**Comment by huysentruitw** [comment]
Apart from having a different UUID, Major, Minor and TX value (which should be the problem here), I see that you're sending 31 bytes, while `Beacon.ToAdvertisingData()` only generates 30 bytes. Can you add a zero to the `result`-array at the end in Beacon.cs `ToAdvertisingData()` method and see if that works?

**Comment by huysentruitw** [comment]
The spec says SetAdvertisingDataCommand takes 31 octets, so this is probably a bug. Waiting for your test results :)

**Comment by huysentruitw** [comment]
So quiet in here, I believe someone is enjoying holidays :)

**Comment by TheScribbler** [comment]
Yes, I can confirm that adding a zero byte fixes the bug, the advertising is working. I figured the missing byte on my own, but I was forced to go on holiday before I could reply. :fearful: :wink:

**Comment by huysentruitw** [comment]
Another issue closed :) Thank you!
