### ISSUE TITLE
Any plans for non-beacon devices?

### ISSUE THREAD

**Issue by dfiverr** [huysentruitw/win-beacon#27]
I have been looking long and hard on the internet, and there is no place to get a working Bluetooth Low Energy stack for Windows 7. Any plans, or any tips on converting this project to become a working Bluetooth Low Energy API for Windows 7?

**Comment by huysentruitw** [comment]
Did you check out this node.js library https://github.com/sandeepmistry/noble ? It also runs on Windows.
