### ISSUE TITLE
Fail to run Beacon detection

### ISSUE THREAD

**Issue by alfanpresekal** [huysentruitw/win-beacon#4]
Last time my error was because I juts implement you code directly huysentruitw , but now it work by change the value of VendorID and ProductID. It can broadcast (advertise) data, I can read the data using android.

But for beacon detection, it still did not work. Do you have any idea why?

Many thanks

**Comment by alfanpresekal** [comment]
Seems something related with this part of code

 hub.BeaconDetected += (sender, e) =>
 {
        Console.WriteLine("Detected beacon: {0}", e.Beacon);
  };

**Comment by huysentruitw** [comment]
I think the problem will be more low level. As there is nothing fancy about that part of the code you've posted. Anyway, I have ordered a Pluggable BT dongle which should have the same VID/PID you're using (hopefully) so I can see what's going on. Will take some time before it arrives, so please have some patients :)

**Comment by alfanpresekal** [comment]
Thanks for the answer, 
What device did you use to successfully run the code? Did you use kind of Windows tablet which has Bluetooth 4.0 or just classic Bluetooth?

**Comment by huysentruitw** [comment]
Today the Pluggable BLE dongle has arrived (ordered from Amazon) with VID: 0A5C and PID: 21E8 and acting-as and receiving beacons works. What brand and exact type of dongle are you using?

Perhaps there are older firmwares that do not support this.

**Comment by alfanpresekal** [comment]
Thanks for update, 
I have two different BLE USB Dongle, one of them (Racksoy) cannot broadcast and read advertisement, another (Plugable) can broadcast but cannot read advertisement.
I try to buy another dongle now. For the detection did you make some filtering or just read all available Bluetooth advertisement packet?. 
If I may know, what kind of PC/Laptop/Tablet did you use. I wonder if the problem related with my Laptop.

**Comment by huysentruitw** [comment]
Packet reception happens in this method: https://github.com/huysentruitw/win-beacon/blob/master/src/WinBeacon.Stack/Controllers/LeController.cs#L130

But for every command a CommandCompleteEvent will be processed. Detecting beacons happens when a `LeMetaEvent` arrives, maybe there is something wrong with the parsing. Once the program is started (so all commands have been sent), you should enable the beacon and set a breakpoint here: https://github.com/huysentruitw/win-beacon/blob/master/src/WinBeacon.Stack/Controllers/LeController.cs#L134

**Comment by huysentruitw** [comment]
Oh and to answer your question about PC/Laptop type, I use a Intel i5 desktop, but also tested on HP Intel i7 laptop. But this should not matter as the library is sending raw commands to the dongle.

**Comment by huysentruitw** [comment]
Hi @alfanpresekal, I don't know if it is possible for you to test the new NuGet package v1.1.0.63 with your Pluggable dongle that didn't work before? I wonder if it is working now. Thank you.

**Comment by huysentruitw** [comment]
Hi @alfanpresekal, I don't know if it is possible for you to test the new NuGet package v1.1.0.71 with your Pluggable dongle that didn't work before? I wonder if it is working now. Thank you.
