### ISSUE TITLE
Can win-beacon list 100 iBeacon in range ?

### ISSUE THREAD

**Issue by tinamore** [huysentruitw/win-beacon#5]
Hi
First, big thank for your great project.
I am building project about iBeacon on windows.I have a question
Can i use win-beacon Lib for detect and get list 100 iBeacon in range.
Thank.
I hope receive your reply soon.

**Comment by huysentruitw** [comment]
Theoretically I don't see a problem as the advertisement packages are connection-less. So I guess it should work.

**Comment by tinamore** [comment]
Thank for response.
Can you give me a sample code use your Lib for get all iBeacon inside range and append UID to list.
Thank you very much.

**Comment by huysentruitw** [comment]
Well I usually don't write code just to write code, but I understand your usage, so I might consider implementing this as a feature and add it to the library.

**Comment by huysentruitw** [comment]
I've written a BeaconCollector class (not sure about the name for now) that should do what you want. Please find it in the commit #10

**Comment by tinamore** [comment]
Thank you for great your work.
I ordered 50 beacon. I will feedback after i receive the item.
Thanks

**Comment by huysentruitw** [comment]
Were you able to test this already?

**Comment by huysentruitw** [comment]
Will close it for now until there is some news on this.
